[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmd = "npm ci --prefer-offline --no-audit"

[phases.build]
cmd = "npm run build"
dependsOn = ["install"]

[start]
cmd = "npx serve dist -s -p $PORT"
