[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.build]
cmds = [
  "rm -rf node_modules package-lock.json",
  "npm install --legacy-peer-deps",
  "npm install @rollup/rollup-linux-x64-gnu --no-save",
  "npm run build"
]

[start]
cmd = "npm run start"
